### ISSUE TITLE
  Port 4443 is not reachable from outside.

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/jitsi_ynh#60]
### Describe the bug

I just installed Jitsi with the latest changes you made. The install went through but I see this error "Port 4443 is not reachable from outside."

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

I am sent to this https://yunohost.org/en/isp_box_config?q=%2Fisp_box_config but I do not self host. So what would be the solution?

I opened the port via the firewall and rebooted the server but still no luck. The Jitsi itself works, even connecting to a meeting I have created. I do not see the video from the other person but the rest works.

I know you guys did a lot of changes recently and maybe this is why, but I am willing to test if that helps.

Cheers!

**Comment by yalh76** [comment]
If you are behind a router or a firewall you also need to redirect external port 4443 to you server, as you made for port http 80 and port https 443

**Comment by yalh76** [comment]
> Same issue here.
> 
> As I do not self-hosting at home/behind a home router, I do not see the need/possibility to change firewall settings.
> 
> The only difference I see to the other ports open on the yunohost server is, that UPnP is not enabled for port 4443 and 10000. Is this a hint?

Maybe ports TCP/4443 and UDP/10000 need to be open at provider level (for example, if you host your server in an OVH vps, you need to allow those ports in the OVH interface)

**Comment by AkselRocks** [comment]
@yalh76 I searched at my provider for the option to change the open ports, but can not find any. And I do not remember ever seen this option. 

Plus I have another VPS at the same provider and there I can open ports via `ufw` and I do not have to change anything at provider level.

My provider is netcup. What is your provider @tio-trom ? Is it maybe a provider issue?

**Comment by yalh76** [comment]
the two ports are needed if coturn is enabled, that's not the case actually

**Comment by tio-trom** [comment]
So I can't simply open the ports via YNH admin? I use a Contabo VPS.

**Comment by AkselRocks** [comment]
The ports are open in yunohost firewall, but yunohost diagnose reports 2 problems, that port 4443 and 10000 is not reachable from outside (plus: metronome not working)

![Bildschirmfoto_2022-02-12_12-37-01](https://user-images.githubusercontent.com/44803148/153724558-92fd7e57-b15d-48ff-8208-e7551b7ec4f1.png)


```
7: 
        details: 
          - Exposing this port is needed for [?] features (service jitsi-videobridge)
          - To fix this issue, you most probably need to configure port forwarding on your internet router as described in https://yunohost.org/isp_box_config
        status: ERROR
        summary: Port 4443 is not reachable from outside.
      8: 
        details: Exposing this port is needed for xmpp features (service metronome)
        status: SUCCESS
        summary: Port 5222 is reachable from outside.
      9: 
        details: Exposing this port is needed for xmpp features (service metronome)
        status: SUCCESS
        summary: Port 5269 is reachable from outside.
      10: 
        details: 
          - Exposing this port is needed for [?] features (service jitsi-videobridge)
          - To fix this issue, you most probably need to configure port forwarding on your internet router as described in https://yunohost.org/isp_box_config
        status: ERROR
        summary: Port 10000 is not reachable from outside.
```

```
      5: 
        details: You can try to restart the service, and if it doesn't work, have a look at the service logs in the webadmin (from the command line, you can do this with 'yunohost service restart metronome' and 'yunohost service log metronome').
        status: ERROR
        summary: Service metronome is dead :(
```
